### ISSUE TITLE
[NOTE] Build Status Notes

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#10]
* Make tier0 and tier1 compilable
* Make launcher compilable but it currently does nothing (it couldn't find filesystem module and should open an error messabebox notify but it's currently disabled so it's stay silent)

P.S: I think that it's currently possible to mount filesystem_stdio and engine modules using this launcher

**Comment by Sh1ft0x0EF** [comment]
* Make filesystem module compilable. Compiled as stdio and null. Stdio currently does nothing. Null is tracing to log in debug.
* Launcher falls back to filesystem_null if filesystem_stdio couldn't be loaded

**Comment by Sh1ft0x0EF** [comment]
Include entries are completely broken for engine module. Need to remove dups of hlsdk headers and revsit every include entry in every file...

**Comment by CrusoeDaWolf** [comment]
Current status of compilation on both Windows and Linux?

**Comment by Sh1ft0x0EF** [comment]
After header fixes rehlds should be buildable + also some parts of client at that time

**Comment by Sh1ft0x0EF** [comment]
But I personally don't count on that because the codebase is still pretty raw

**Comment by CrusoeDaWolf** [comment]
Alright, I will keep trying to compile on Linux until something finally happens!

**Comment by Sh1ft0x0EF** [comment]
You could try to compile filesystem module - it should be compilable

**Comment by Sh1ft0x0EF** [comment]
dbg module should be buildable too but I didn't tried to build it yet

**Comment by Sh1ft0x0EF** [comment]
[Engine] Log of sources are dependent on system.hpp. It was fixed and now compilable. After that there was another problem appeared - gcc and __FUNCTION__ macro. Since version 3.4 this is not a macro, but the unrolled local variable of each func and can't be used like

> Sys_Error(__FUNCTION__ " after host_initialized");

Each func call of this kind will be fixed and most sources of the module should finally became builable

**Comment by CrusoeDaWolf** [comment]
Can it compile using cmake yet?

**Comment by Sh1ft0x0EF** [comment]
Not all sources are buildable yet - need to rewrite includes for them. ReHLDS precompiled header has an engine.h entry which contains all engine header entries but this approach cause to recompile the precompiled every engine header change which makes this pch useless
And cmake files aren't fully done yet
I will update them soon but the engine isn't fully buildable yet anyway

**Comment by Sh1ft0x0EF** [comment]
VS projects are currently a bit outdated
I'm using MinGW and [this](http://vaultec.mbnet.fi/mingwstudio.php)

**Comment by CrusoeDaWolf** [comment]
How much of the engine is finished btw? I'm still very interested in this project!

**Comment by Sh1ft0x0EF** [comment]
Client side is still pretty raw

**Comment by CrusoeDaWolf** [comment]
On Linux, there seems to be an issue with the CMakeLists.txt and it gives me this:

`CMake Error at ogs/engine/CMakeLists.txt:42 (else):
  else An ELSE command was found outside of a proper IF ENDIF structure.  Or
  its arguments did not match the opening IF command.


CMake Error at ogs/engine/CMakeLists.txt:44 (elseif):
  elseif An ELSEIF command was found outside of a proper IF ENDIF structure.


CMake Error at ogs/engine/CMakeLists.txt:46 (else):
  else An ELSE command was found outside of a proper IF ENDIF structure.  Or
  its arguments did not match the opening IF command.


CMake Error at ogs/engine/CMakeLists.txt:47 (message):
  Unsupported platform!
`
When looking at the CMakeLists.txt file, specifically lines 42, 44, 46, shouldn't it be like `if`, `elseif`, `else` or something similar?

**Comment by Sh1ft0x0EF** [comment]
Yeah, there is a mistype
https://github.com/Sh1ft0x0EF/OpenGoldSrc/blob/dev/ogs/engine/CMakeLists.txt#L42
Fixed

**Comment by Sh1ft0x0EF** [comment]
Alright.
For now all the code placed in engine/butcherpete should be buildable
It's not linkable in a single dll yet, but should at least be compilable without errors

**Comment by Sh1ft0x0EF** [comment]
* Make engine module finally buildable (currently only by MSVC compiler)
It is pretty bad in functionality but at least can be built
Further builds will be more functional

**Comment by CrusoeDaWolf** [comment]
Congrats! At least this project is getting somewhere! :D

**Comment by Sh1ft0x0EF** [comment]
Commented out some stuff for now and compiled it
Build 0004
Can be loaded by hlds.exe from ReHLDS Team (that compiled by MSVC if I think right; MinGW would probably crash/fail to load the msvc dll?)
It just does nothing, but it's motivating do go further

![itsalive](https://cloud.githubusercontent.com/assets/10573466/24174046/b2f9e0f4-0e9f-11e7-98cc-3dfba4994304.png)

**Comment by Sh1ft0x0EF** [comment]
* Note for pre-build 0012:
Comment out the usage of the console module from the host class code and remove all the console code files from the msvc project if you want to build it

**Comment by Sh1ft0x0EF** [comment]
[Engine]
### Build 0012:
* Put the filesystem module in use (works only at CDedicatedServerAPI level, need to pass it to engine via Load I think...; don't see any other posibilities for now); Checked with filesystem_null (the old build of fileesystem with tracing to log) - it mounts and that's it for now (TODO: should be unmounted cause we have this call inside the CDedicatedServerAPI::Shutdown but it doesn't get called atm);
* Some additions to CFile class;
* New CStringHandler class - set of static funcs to handle strings;
* Initial CCmdLine class that should replace the COM_CheckArg; COM_InitArgv; Sys_InitArgv and such; Probably will be replaced with the impl that already present in launcher code

**Comment by Sh1ft0x0EF** [comment]
# [Engine]
### Build 0014:
* Partially restore the usage of network system;
* Partially restore the console; Printf/DevPrintf is currently echoes the message to the remote console (dedicated server console) in Debug build;
* Merge some COM_ funcs with CFileSystem (FS oriented funcs)

**Comment by mittorn** [comment]
Do not use aggregate returns and arguments in API, do not use C++ API (even COM is not fully portable), do not use SSE in minGW  and mixing of msvc and mingw binaries will work correctly

**Comment by Sh1ft0x0EF** [comment]
Wow

**Comment by Sh1ft0x0EF** [comment]
@mittorn , it will use the C++ API, but in portable manner (using POD data types, virtual interfaces or structs of them)
There could be some issue with virtual destructor which will be part of the vtable if I declare it (but I don't need it since I'm not gonna free resource by some other module than create it)
I'm not planning to use the C API for new parts here, only and maybe after the C++ API will be done

**Comment by mittorn** [comment]
https://stackoverflow.com/questions/12006854/why-the-size-of-a-pointer-to-a-function-is-different-from-the-size-of-a-pointer

**Comment by mittorn** [comment]
Also, update dll loader, it have fixed some bugs

**Comment by Sh1ft0x0EF** [comment]
@mittorn , it's already updated, you're looking at outdated code base
https://github.com/headcrab-garage/OpenGoldSrc/tree/dev/ogs/ogsnext/dll_loader

**Comment by Sh1ft0x0EF** [comment]
@mittorn 
> Do not use aggregate returns and arguments in API, do not use C++ API (even COM is not fully portable), do not use SSE in minGW and mixing of msvc and mingw binaries will work correctly

Links plz

**Comment by Sh1ft0x0EF** [comment]
I'm merging the repo with reogs
It currently needs to select the gsr implementations of the modules and use the Visual Studio/MSBuild in order to build them for now
I need to fix the SourceSDK to properly support MinGW
Engine code is still broken but some parts are buildable. The other are missing include entries or weren't updated to use the GS structs and still expects to find Quake-specific entries in client/server structs and such

**Comment by Sh1ft0x0EF** [comment]
Applied rehlds version of world.cpp
Hopefully, it fixes all the errors in that file
Same for sv_user.cpp
Some errors are still present in wad.cpp
rehlds-specific code should be commented out from the server code for now

**Comment by Sh1ft0x0EF** [comment]
Applying the old server code + qw server code above the rehlds version (mostly checking the logic and adding the original code comments to rehlds)
Also applying the client side of qw to current netquake+gsr
After that the qw merging will be finally done
And there is almost a full set of Q2 sources!
Well, i won't be applying the q2 fully here, just some codebase fixes and such things here and there
Major part of the gs client-side protocol 48 is already done in the previous iteration (evol-old folder)

**Comment by Sh1ft0x0EF** [comment]
Added some missing definitions, fixed some platform checks for goldsrc-sdk and quakedef.h (which includes mostly all of the engine module headers) is now compilable

**Comment by Sh1ft0x0EF** [comment]
Mostly done with GSR merging (still need to apply the rehlds)
Current engine iteration is NetQuake -> QuakeWorld above it -> GSR and ReHLDS above it -> Q2 render and fixes above them
For now, the codebase consists of mostly broken code but I'm working on it (and I could use some help!)
I'm planning to release an alpha on 9th of October (first repo commit = 1 year of development) but I need some extra pair(s) of hands for that

**Comment by Sh1ft0x0EF** [comment]
@mittorn , I think you're talking about binding a class method to a function pointer
That's not possible and compiler won't let you do that
But you can use wrappers instead
Here's how Magenta implements the legacy engine API (still WIP):
https://github.com/headcrab-garage/magenta/blob/dev/mgt/optional/hlcompat/server/unused/EngineFuncs.cpp
That's the generic way to provide the C API from the C++ program (that use classes) and this approach will be used even for script functions (for AngelScript and such)

**Comment by Sh1ft0x0EF** [comment]
Can't build any of the engine modules because Source SDK is a piece of shi...
Currently fixing the preprocessor definitions in goldsrc-sdk
Next, it will be connected with the hlsdk-core via submodule or subtree (code duplication) and then it should finally compile and work as expected
Probably it will take about 1-2 days for that

**Comment by Sh1ft0x0EF** [comment]
UPDATE:
* fs module is buildable;
* tier0 is partially buildable; lacks some functions functionality; some files still need to be fixed; currently compiles with unresolved symbols at linking stage;
* both launcher versions are broken and win-specific atm;

**Comment by Sh1ft0x0EF** [comment]
UPDATE:
* tier1 is partially buildable;
* dedicated launcher is compilable but unbuildable because of unresolved symbols (still need to provide the sources from "goldsrc/common" folder);

**Comment by Sh1ft0x0EF** [comment]
ReHLDS merge note
Engine module: 41 sources + 43 headers remaining

**Comment by Sh1ft0x0EF** [comment]
UPD:
ReHLDS Merge Status
Engine module: 33 sources + 40 headers remaining

**Comment by Sh1ft0x0EF** [comment]
UPD:
* Almost done with GameUI code fixing; It requires to fix some files and then fix the linking stage;
* Planning to clone the file and content structure from the original (internal) render code; It will be merged then with it and it will be compiled as a dll for evol and as static lib for internal use for vanilla;

**Comment by Sh1ft0x0EF** [comment]
High priority:
GameUI code fixing (+1 day);
VGUI2 code fixing (+2-5 days);
RenderDLL should be fixed (+2-5 days);
ReHLDS API implementations (+1-2 days);
Engine (+5-10 days);

Low priority:
Local impl of fs module should be merged with rehlds (+2-3 days);
Hookers (+1-2 days);
Unittests (+1-2 days);
Testsuite (+1-2 days);
