### ISSUE TITLE
Docs directory needs some structure and porting to Wiki pages

### ISSUE THREAD

**Issue by hhirsch** [headcrab-garage/OpenGS#27]
Hello,

the docs directory could use some structure.
The nesting looks confusing docs/docs/data. 
And the files could be converted to markdown for better readability.

There is some information there that is Quake specific. I am sure things like
```
Mount the Quake CD as one would usually mount a CDROM, this can be 
accomplished by using the command:

		mount /dev/cdrom /mnt
```
are no longer relevant.

I am sure this has no high priority. I am bringing it up because it is a nice beginner task to get some PRs
going. And it will make the repo tidier and less confusing in the progress.

**Comment by Sh1ft0x0EF** [comment]
These docs are still WIP and the Quake-specific meant to be removed
The main goal is to preserve the info about the cvars/cmdline args descriptions and such without any Quake-specific way of setup/work
Any helpful PRs and help are appreciated

**Comment by Sh1ft0x0EF** [comment]
UPD: I think it may be better to make new wiki pages from fixed docs files

**Comment by Sh1ft0x0EF** [comment]
You also need to use the [rw17-dev](https://github.com/projectogs/OpenGoldSrc/tree/rw17-dev) branch since it's the most up-to-date right now

**Comment by Sh1ft0x0EF** [comment]
Docs were moved [here](https://github.com/projectogs/ogs-docs)

**Comment by BlackPhrase** [comment]
@hhirsch , are you still planning to provide any help to the project?

**Comment by hhirsch** [comment]
@BlackPhrase Not atm. Life and GlPortal are keeping me busy. Don't hesitate to contact me though.
