### ISSUE TITLE
Fix CMake files/build

### ISSUE THREAD

**Issue by hhirsch** [headcrab-garage/OpenGS#31]
linus at nasa in ~/system/projects/c++/OpenGoldSrc (rw17-dev)
$ cmake ./
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at ogs/CMakeLists.txt:19 (add_subdirectory):
  The source directory

    /home/linus/system/projects/c++/OpenGoldSrc/ogs/engine

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/linus/system/projects/c++/OpenGoldSrc/CMakeFiles/CMakeOutput.log".

**Comment by Sh1ft0x0EF** [comment]
Current CMakeLists are a bit out-of-date
