### ISSUE TITLE
Out-of-sync with ReHLDS

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#33]
Need to update the sources with updates from ReHLDS
Need to either:
* Apply commit from the beginning of February - to latest commit;
* Clone the latest available ReHLDS code base, apply clang-format on files and the same folder structure and then check for differences in WinMerge (or something else)

**Comment by Sh1ft0x0EF** [comment]
Still actual
Currently using the mid-Aug '17 base
Should apply ALL later commits after the merge will be done
