### ISSUE TITLE
Old Quake (software) render remnants

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#54]
https://github.com/headcrab-garage/ReOGS/blob/858c967e454abd447f591eb29a01efe72cedead3/rehlds-master/rehlds/engine/vid_null.h
https://github.com/headcrab-garage/ReOGS/blob/858c967e454abd447f591eb29a01efe72cedead3/rehlds-master/rehlds/engine/vid_null.cpp

Most of them are simply unused so I won't be using them and replace the whole thing with Q2 render (I mean render dll, it doesn't matter which render it would be later)

**Comment by Sh1ft0x0EF** [comment]
VID_Shutdown is unused?

**Comment by Sh1ft0x0EF** [comment]
GSR contains a call to GL_Config which is not present in rehlds...

**Comment by Sh1ft0x0EF** [comment]
VID_Init accepts an unsigned short (16bit palette) in GS and unsigned char (8bit palette) in NetQuake/QW
But Q2 render doesn't accept anything (I'm sure it uses another way to pass it to sw render)
This thing should be fixed
