### ISSUE TITLE
Q2 render integration

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#56]
Current list of used methods of render interface exports (some of them shouldn't be used)

- [x] qboolean	(*Init) ( void *hinstance, void *wndproc );
- [x] void	(*Shutdown) (void);
- [ ] void	(*BeginRegistration) (char *map);
- [ ] struct model_s *(*RegisterModel) (char *name);
- [ ] struct image_s *(*RegisterSkin) (char *name);
- [x] struct image_s *(*RegisterPic) (char *name);
- [x] void	(*SetSky) (char *name, float rotate, vec3_t axis);
- [ ] void	(*EndRegistration) (void);
- [x] void	(*RenderFrame) (refdef_t *fd);
- [x] void	(*DrawGetPicSize) (int *w, int *h, char *name);	// will return 0 0 if not found
- [x] void	(*DrawPic) (int x, int y, char *name);
- [ ] void	(*DrawStretchPic) (int x, int y, int w, int h, char *name);
- [x] void	(*DrawChar) (int x, int y, int c);
- [x] void	(*DrawTileClear) (int x, int y, int w, int h, char *name);
- [x] void	(*DrawFill) (int x, int y, int w, int h, int c);
- [ ] void	(*DrawFadeScreen) (void);
- [ ] void	(*DrawStretchRaw) (int x, int y, int w, int h, int cols, int rows, byte *data);
- [x] void	(*CinematicSetPalette)( const unsigned char *palette);
- [x] void	(*BeginFrame)( float camera_separation );
- [x] void	(*EndFrame) (void);
- [x] void	(*AppActivate)( qboolean activate );

* Both RegisterModel and RegisterSkin are used in cl_ents in Q2
* RegisterSkin will be removed
* DrawStretchRaw is in cl_cin
* BeginRegistration/EndRegistration are in cl_view (which is view previously)

**Comment by Sh1ft0x0EF** [comment]
Q2 doesn't have draw.h and render.h header files in engine code because they're functionality was moved to render dll and now they supposed to be accessed via the render exports
But GS expects to find the Q1 render
Maybe I should implement the draw and render functions inside the engine which forwards the calls to the render dll...

**Comment by Sh1ft0x0EF** [comment]
Carmack upgraded the Q1 rendering code to Q2 version and placed it in its own dll
And now we downgrading that code back to Q1...
(Pretty smart I'd say)
Despite that, I'm planning to merge the Q1 rendering code with our Q2 version and it will be still in it's own folder out of the engine
It will be integrated with engine module for "vanilla" build and split into dll for "evol"
More details a bit later
