### ISSUE TITLE
VGUI and other compiler-specific exports from libs

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#6]
I'm not sure if original GS should be linked with vgui lib or it's handled by GameUI module but anyway we couldn't link vgui with target module on MinGW.
Additionally, we have a set of tier* libs that have compiler-dependent implementations. The solutions are:

1) Compile GameUI (target module) by MSVC compiler
2) VGUI wrapper module that would be compiled by MSVC and provide C api from itself. Then the target module (engine/GameUI) would be compiler independent
3) Static-linkage?
4) Custom implementations of these modules that uses interfaces? But this way we couldn't link with original modules

That would be problematically...

UPD: tier* libs doesn't have any import lib so we need our own impl anyway (or from SourceSDK)

**Comment by Sh1ft0x0EF** [comment]
About VGUI - I think it can be partially be solved by VGUI2 cause it uses virtual interfaces

**Comment by Sh1ft0x0EF** [comment]
UPD: all compiled version of engine module are hardly linked with that f** vgui lib
