### ISSUE TITLE
SDL2 notes

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#61]
sys_sdlwind.cpp (impl of IGame interface)
snd_sdl.cpp
keys.cpp

Are sdl-dependent (6153-like)
These sources should be put into specific folder with all other sdl implementations of the engine components
Keys aren't fully sdl-dependent but contain "engine key <-> sdl key" converting functions
For non-sdl implementations (4554-like), additional sys_linuxwind and sys_mainwindow should be added
sys_sdl in partially done and should be finished (?)
sys_linuxwind should be blank (looks like)
sys_mainwindow is win-specific impl

**Comment by Sh1ft0x0EF** [comment]
Also, some of the engine parts are using the utility sdl functions (like opening a message box and such)
I think that for these cases an additional preprocessor define should be added (OGS_USE_SDL or something)

**Comment by Sh1ft0x0EF** [comment]
List of SDL2 imports (hw.dll):

SDL_CreateRGBSurfaceFrom
SDL_CreateSystemCursor
SDL_CreateWindow
SDL_DestroyWindow
SDL_FreeCursor
SDL_FreeSurface
SDL_GL_CreateContext
SDL_GL_GetAttribute
SDL_GL_GetProcAddress
SDL_GL_SetAttribute
SDL_GL_SetSwapInterval
SDL_GL_SwapWindow
SDL_GetClosestDisplayMode
SDL_GetDisplayBounds
SDL_GetDisplayMode
SDL_GetError
SDL_GetKeyFromScancode
SDL_GetModState
SDL_GetMouseState
SDL_GetNumDisplayModes
SDL_GetRelativeMouseState
SDL_GetWindowPosition
SDL_GetWindowSize
SDL_GetWindowWMInfo
SDL_InitSubSystem
SDL_PollEvent
SDL_PumpEvents
SDL_Quit
SDL_QuitSubSystem
SDL_SetCursor
SDL_SetHint
SDL_SetRelativeMouseMode
SDL_SetWindowDisplayMode
SDL_SetWindowFullscreen
SDL_SetWindowGrab
SDL_SetWindowIcon
SDL_SetWindowPosition
SDL_SetWindowSize
SDL_ShowCursor
SDL_ShowSimpleMessageBox
SDL_ShowWindow
SDL_WaitEventTimeout
SDL_WarpMouseInWindow
SDL_WasInit
