### ISSUE TITLE
[QUESTION] Can OGS compile on Linux?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [headcrab-garage/OpenGS#7]
Can OGS compile on Linux yet, or are there still things to fix?

**Comment by Sh1ft0x0EF** [comment]
It can't be compiled even on Windows right now

**Comment by CrusoeDaWolf** [comment]
RIP. Gonna keep this closed for now.

**Comment by Sh1ft0x0EF** [comment]
Stay tuned on #10

**Comment by Sh1ft0x0EF** [comment]
We're pretty close now. Gonna keep this open for now

**Comment by Sh1ft0x0EF** [comment]
@CrusoeDaWolf 
That's pretty nice question
Travis is broken so you can try to build it yourself
