### ISSUE TITLE
6153 vstdlib exports

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#75]
Export entries from the 6153 version of vstdlib:

CommandLine
Coroutine_Cancel
Coroutine_Continue
Coroutine_Create
Coroutine_DebugBreak
Coroutine_GetCurrentlyActive
Coroutine_GetStackDepth
Coroutine_IsActive
Coroutine_ReleaseThreadMemory
Coroutine_Test
Coroutine_ValidateGlobals
Coroutine_YieldToMain
CreateInterface
GetNameFromOSType
GetOSType
GetOSTypeFromString
InstallUniformRandomStream
KeyValuesSystem
Q_AppendSlash
Q_BasicHtmlEntityEncode
Q_ComposeFileName
Q_CopyAndFixSlashes
Q_DefaultExtension
Q_ExtractFileExtension
Q_ExtractFilePath
Q_FileBase
Q_FixSlashes
Q_FormatAndAppend
Q_FormatAndAppendTail
Q_GetFileExtension
Q_IsAbsolutePath
Q_MakeAbsolutePath
Q_NormalizeUTF8
Q_NormalizeUTF8Old
Q_RemoveDotSlashes
Q_ReplaceBadFilenameCharacters
Q_SetExtension
Q_SplitString
Q_SplitString2
Q_StrLeft
Q_StrRight
Q_StrSlice
Q_StrSubst
Q_StrSubstInPlace
Q_StrTrim
Q_StripExtension
Q_StripFilename
Q_StripLastDir
Q_StripPrecedingAndTrailingWhitespace
Q_StripTrailingSlash
Q_UTF8ToUnicode
Q_UnicodeToUTF8
Q_UnqualifiedFileName
Q_atof
Q_atoi
Q_binarytohex
Q_hextobinary
Q_pretifymem
Q_pretifynum
Q_snprintf
Q_strcasecmp
Q_strcat
Q_stristr
Q_strnappend
Q_strncasecmp
Q_strncat
Q_strnchr
Q_strncmp
Q_strncpy
Q_strnicmp
Q_strnistr
Q_strnlen
Q_strtowcs
Q_vsnprintf
Q_vsnprintfRet
Q_wcscat
Q_wcsncpy
Q_wcstostr
RandomFloat
RandomGaussianFloat
RandomInt
RandomSeed
VStdLib_GetICVarFactory
_Q_memcmp
_Q_memcpy
_Q_memmove
_Q_memset
_Q_strcmp
_Q_stricmp
_Q_strlen
_Q_strlower
_Q_strrchr
_Q_strstr
_Q_strupr
_Q_wcscmp
_Q_wcslen
CCommandLineParam::CCommandLineParam(char const *,char const *)
CGaussianRandomStream::CGaussianRandomStream(class IUniformRandomStream *)
CUniformRandomStream::CUniformRandomStream(class CUniformRandomStream const &)
CUniformRandomStream::CUniformRandomStream(void)
CCommandLineParam::~CCommandLineParam(void)
class CCommandLineParam & CCommandLineParam::operator=(class CCommandLineParam const &)
class CGaussianRandomStream & CGaussianRandomStream::operator=(class CGaussianRandomStream const &)
class CStringNormalization & CStringNormalization::operator=(class CStringNormalization const &)
class CUniformRandomStream & CUniformRandomStream::operator=(class CUniformRandomStream const &)
const CUniformRandomStream::`vftable'
void CGaussianRandomStream::`default constructor closure'(void)
void CGaussianRandomStream::AttachToStream(class IUniformRandomStream *)
bool CCommandLineParam::Exists(void)
int CUniformRandomStream::GenerateRandomNumber(void)
int CCommandLineParam::GetHParam(void)
void CStringNormalization::Initialize(void)
int CStringNormalization::Normalize(bool,char const *,char *,int)
int CStringNormalization::Normalize(bool,wchar_t const *,wchar_t *,int)
char const * Q_stristr(char const *,char const *)
float CGaussianRandomStream::RandomFloat(float,float)
float CUniformRandomStream::RandomFloat(float,float)
int CUniformRandomStream::RandomInt(int,int)
void CUniformRandomStream::SetSeed(int)
bool CStringNormalization::Test_BValidateStructures(void)
void CStringNormalization::ValidateStatics(class CValidator &,char *)
bool CStringNormalization::m_bInitialized

**Comment by Sh1ft0x0EF** [comment]
TODO: Check for presence of these entries

Q_AppendSlash
Q_BasicHtmlEntityEncode
Q_ComposeFileName
Q_CopyAndFixSlashes
Q_DefaultExtension
Q_ExtractFileExtension
Q_ExtractFilePath
Q_FileBase
Q_FixSlashes
Q_FormatAndAppend
Q_FormatAndAppendTail
Q_GetFileExtension
Q_IsAbsolutePath
Q_MakeAbsolutePath
Q_NormalizeUTF8
Q_NormalizeUTF8Old
Q_RemoveDotSlashes
Q_ReplaceBadFilenameCharacters
Q_SetExtension
Q_SplitString
Q_SplitString2
Q_StrLeft
Q_StrRight
Q_StrSlice
Q_StrSubst
Q_StrSubstInPlace
Q_StrTrim
Q_StripExtension
Q_StripFilename
Q_StripLastDir
Q_StripPrecedingAndTrailingWhitespace
Q_StripTrailingSlash
Q_UTF8ToUnicode
Q_UnicodeToUTF8
Q_UnqualifiedFileName
Q_binarytohex
Q_hextobinary
Q_pretifynum

Q_strnappend
Q_strnchr

Q_strnistr
Q_strnlen
Q_strtowcs
Q_vsnprintfRet
Q_wcscat
Q_wcsncpy
Q_wcstostr

_Q_wcscmp
_Q_wcslen

CUniformRandomStream::CUniformRandomStream(class CUniformRandomStream const &)

class CGaussianRandomStream & CGaussianRandomStream::operator=(class CGaussianRandomStream const &)

class CUniformRandomStream & CUniformRandomStream::operator=(class CUniformRandomStream const &)
const CUniformRandomStream::`vftable'

void CGaussianRandomStream::`default constructor closure'(void)

**Comment by Sh1ft0x0EF** [comment]
vstdlib should expose the ICvar interface version 002
Should look like this (Source SDK 2006 version):
https://github.com/Weeabooru/source-sdk-2006/blob/a168e5921cdc57400e4d906c182b1a50b5c22d86/public/icvarv02.h

**Comment by Sh1ft0x0EF** [comment]
It also probably should use the ICommandLine interface from 2006, not 2003...

**Comment by Sh1ft0x0EF** [comment]
Our current exports:

Coroutine_Cancel
Coroutine_Continue
Coroutine_Create
Coroutine_DebugAssert
Coroutine_DebugBreak
Coroutine_GetCurrentlyActive
Coroutine_GetStackDepth
Coroutine_IsActive
Coroutine_ReleaseThreadMemory
Coroutine_Test
Coroutine_ValidateGlobals
Coroutine_YieldToMain
CreateInterface
GetNameFromOSType
GetOSType
GetOSTypeFromString
InstallUniformRandomStream
Q_wcscat
RandomFloat
RandomGaussianFloat
RandomInt
RandomSeed
VStdLib_GetICVarFactory
_ZN17CCommandLineParam6ExistsEv
_ZN17CCommandLineParam9GetHParamEv
_ZN17CCommandLineParamC1EPKcS1_
_ZN17CCommandLineParamC2EPKcS1_
_ZN17CCommandLineParamD1Ev
_ZN17CCommandLineParamD2Ev
_ZN20CStringNormalization10InitializeEv
_ZN20CStringNormalization15ValidateStaticsER10CValidatorPc
_ZN20CStringNormalization24Test_BValidateStructuresEv
_ZN20CStringNormalization9NormalizeEbPKcPci
_ZN20CStringNormalization9NormalizeEbPKwPwi
_ZN20CUniformRandomStream11RandomFloatEff
_ZN20CUniformRandomStream20GenerateRandomNumberEv
_ZN20CUniformRandomStream7SetSeedEi
_ZN20CUniformRandomStream9RandomIntEii
_ZN20CUniformRandomStreamC1Ev
_ZN20CUniformRandomStreamC2Ev
_ZN21CGaussianRandomStream11RandomFloatEff
_ZN21CGaussianRandomStream14AttachToStreamEP20IUniformRandomStream
_ZN21CGaussianRandomStreamC1EP20IUniformRandomStream
_ZN21CGaussianRandomStreamC2EP20IUniformRandomStream
_ZTI20CUniformRandomStream
_ZTI20IUniformRandomStream
_ZTI27CDefaultUniformRandomStream
_ZTV20CUniformRandomStream
_ZTV20IUniformRandomStream
_ZTV27CDefaultUniformRandomStream

**Comment by Sh1ft0x0EF** [comment]
It's now easier to say which symbols are not exported yet:

Q_BasicHtmlEntityEncode
Q_ComposeFileName
Q_CopyAndFixSlashes
Q_DefaultExtension
Q_FormatAndAppend
Q_FormatAndAppendTail
Q_MakeAbsolutePath
Q_NormalizeUTF8
Q_NormalizeUTF8Old
Q_ReplaceBadFilenameCharacters
Q_SetExtension
Q_StrSubstInPlace
Q_StrTrim
Q_StripPrecedingAndTrailingWhitespace
Q_UTF8ToUnicode
Q_UnicodeToUTF8

Q_snprintf
Q_strcasecmp
Q_strcat
Q_stristr
Q_strnappend
Q_strncasecmp
Q_strncat
Q_strnchr
Q_strncmp
Q_strnicmp
Q_strnistr
Q_strnlen

Q_wcsncpy

char const * Q_stristr(char const *,char const *)

bool CStringNormalization::m_bInitialized

**Comment by Sh1ft0x0EF** [comment]
vstdlib is required for:
* ServerBrowser;
