### ISSUE TITLE
One engine module for both execution modes

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#79]
GS was based on the WinQuake sources so it contains a set of checks for (client state == dedicated) for some client-side specific code
It won't initialize some client-side functionality for dedicated server mode
But it still will be using the client-side state structures across the codebase
That means that SWDS-specific build for dedicated server is kinda useless
Current version of 6153 swds module still linked againt SDL2, vgui (and looks like it's the same renamed sw module)
In order to reduce the impact there is possibility to modify the Host_Frame contents and use the function pointer that will contain only needed code (Host_DedicatedFrame contains only server-side calls and Host_ListenFrame contains both cl/sv calls)
The one reason to use the SWDS-specific build is to get rid of vgui/SDL2 which is done in rehlds, but original hlds still uses them for no reason

**Comment by Sh1ft0x0EF** [comment]
Still unsure about that
Source does use a single dll for both modes (despite that its codebase is full of "SWDS" conditional compilation lines)
It will require linking with SDL2 even if it won't be used in dedicated server mode or only minor parts of it
ReHLDS doesn't require it at all but it still contains a lot of stub client-side functionality
It's possible to move the client-side functionality from the engine to another module, but it would be closer to rw17 and farther from the authentic architecture
