### ISSUE TITLE
common/interface - public/interface - public/tier1/interface

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#80]
* common/interface <- pre 2.4 hlsdk;
* public/interface <- since 2.4 hlsdk; (common/interface is still there)
* public/tier1/interface <- V moved some of the "public/" code into this lib so interface is now (should be there) there;

BUT

HLSDK2.4 came out in 2013 and at that time GS already had a tier1 lib
So it looks like they moved it from tier1 back to public...

**Comment by Sh1ft0x0EF** [comment]
I probably was just blind, but the structure of "public/interface.h" file is following:
```cpp
#if _MSC_VER >= 1300 // Visual Studio 7.0 (aka .NET 2002) or higher
#include "tier1/interface.h"
#else // if Visual Studio 6.0
// ...
#endif
```

No idea why 7.0 required the special treatment and maybe it doesn't matter now...
Maybe tier1' version contains code that's won't compile on VS6?
