### ISSUE TITLE
tier1/strtools -> vstdlib/strtools

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#81]
strtools should be placed in vstdlib for GS

But these funcs could be useful across the codebase (already in use by rehlds code)
vstdlib will contain them exported
but other modules still will be able to use them internally if needed

**Comment by Sh1ft0x0EF** [comment]
strtools is broken
strtools_unicode probably should be placed inside the vstdlib too, or, according to rehlds, inside the engine module (not sure about that cause they don't use the tier libs)

**Comment by Sh1ft0x0EF** [comment]
That's right:
https://github.com/SteamDatabase/SteamTracking/blob/master/BuildbotPaths/steamservice.txt

**Comment by BlackPhrase** [comment]
It's possible for GS to use the strtools set across the codebase and having only one definition:
usage of static version of vstdlib (pretty sure it's implemented this way in GS);

Also, link above contains the following line:
> /Users/buildbot/buildslave/steam_rel_client_osx/build/src/vstdlib/debugstatssystem.cpp
Might be related to steam only but who knows...
