### ISSUE TITLE
Add possibility to compile tier0 & vstdlib as static libraries

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#87]
I think the whole magic behind internal implementations of some tier0/vstdlib interfaces inside some modules is simple:
**These modules are linked with tier0 (and vstdlib) statically**
I can't confirm that but that's probably how it is
Source contains vpc scripts which don't support a static lib build type (if I remember right)
**But almost each of the Source modules depends on tier0 and some of them also on vstdlib dlls**
SRCDS launcher depends on tier0 and vstdlib but HLDS doesn't simply because it's linked to them statically
VPC scripts don't support static lib build type because it's unneeded for Source modules
But GS don't use vpc scripts (I guess it only has MSVC(6) projects)
So you can't clearly say that tier0/vstdlib shouldn't always be dlls only
Both tier0 and vstdlib should be compiled with special macros defined for dll (for function exporting)
And there is support for the static version which at least was used for GS

**Comment by Sh1ft0x0EF** [comment]
Looks like a final piece of the puzzle
